// apps/sandbox/app/page.tsx
import { Button, type ButtonSize, type ButtonVariant } from '@venice-sistemas/react';

/**
 * Server Component renderizando componentes client — a composição normal do App
 * Router, e a que mais quebra em biblioteca mal empacotada. Note que não há
 * "use client" aqui: se ele fosse necessário, a diretiva não teria sobrevivido ao
 * bundle do pacote.
 */

const VARIANTS: ButtonVariant[] = ['default', 'destructive', 'outline', 'secondary', 'ghost', 'link'];
const SIZES: ButtonSize[] = ['default', 'sm', 'lg'];

function Row({ label, children }: { label: string; children: React.ReactNode }) {
  return (
    <div style={{ display: 'flex', alignItems: 'center', gap: 'var(--rp-space-md)', flexWrap: 'wrap' }}>
      <span
        style={{
          width: '9rem',
          fontFamily: 'var(--rp-typography-family-mono)',
          fontSize: 'var(--rp-typography-caption-md-size)',
          color: 'var(--rp-color-text-secondary)',
        }}
      >
        {label}
      </span>
      {children}
    </div>
  );
}

export default function Page() {
  return (
    <main style={{ display: 'flex', flexDirection: 'column', gap: 'var(--rp-space-xl)', maxWidth: '52rem' }}>
      <div>
        <h1 style={{ fontSize: 'var(--rp-typography-heading-page-size)', margin: 0 }}>Sandbox</h1>
        <p style={{ color: 'var(--rp-color-text-secondary)', marginTop: 'var(--rp-space-xs)' }}>
          Next.js sem Tailwind, consumindo o pacote publicado.
        </p>
      </div>

      {VARIANTS.map((variant) => (
        <Row key={variant} label={variant}>
          {SIZES.map((size) => (
            <Button key={size} variant={variant} size={size}>
              Registrar
            </Button>
          ))}
          <Button variant={variant} disabled>
            Desabilitado
          </Button>
          <Button variant={variant} loading>
            Carregando
          </Button>
        </Row>
      ))}

      <Row label="só ícone">
        {/* aria-label obrigatório: sem ele o componente avisa no console em dev. */}
        <Button aria-label="Fechar" variant="ghost">
          ✕
        </Button>
      </Row>
    </main>
  );
}

// apps/sandbox-angular/src/app.component.ts
import { Component } from '@angular/core';
import { RpButton, type ButtonSize, type ButtonVariant } from '@venice-sistemas/angular';

/**
 * Espelha a página do sandbox Next, de propósito: as duas lado a lado devem ser
 * indistinguíveis. Se divergirem, alguma plataforma acrescentou classe por fora
 * da receita compartilhada — que é o único jeito de isso acontecer.
 */
@Component({
  selector: 'rp-app',
  standalone: true,
  imports: [RpButton],
  host: {
    style:
      'display:block;padding:var(--rp-space-2xl);background:var(--rp-color-surface-page);color:var(--rp-color-text-primary);font-family:var(--rp-typography-family-default);min-height:100vh',
  },
  template: `
    <main style="display:flex;flex-direction:column;gap:var(--rp-space-xl);max-width:52rem">
      <div>
        <h1 style="font-size:var(--rp-typography-heading-page-size);margin:0">Sandbox Angular</h1>
        <p style="color:var(--rp-color-text-secondary);margin-top:var(--rp-space-xs)">
          Angular sem Tailwind, consumindo o mesmo pacote publicado
        </p>
      </div>

      @for (variant of variants; track variant) {
        <div style="display:flex;align-items:center;gap:var(--rp-space-md);flex-wrap:wrap">
          <span
            style="width:9rem;font-family:var(--rp-typography-family-mono);font-size:var(--rp-typography-caption-md-size);color:var(--rp-color-text-secondary)"
          >{{ variant }}</span>

          @for (size of sizes; track size) {
            <rp-button [variant]="variant" [size]="size">Registrar</rp-button>
          }
          <rp-button [variant]="variant" [disabled]="true">Desabilitado</rp-button>
          <rp-button [variant]="variant" [loading]="true">Carregando</rp-button>
        </div>
      }
    </main>
  `,
})
export class App {
  readonly variants: ButtonVariant[] = ['default', 'destructive', 'outline', 'secondary', 'ghost', 'link'];
  readonly sizes: ButtonSize[] = ['default', 'sm', 'lg'];
}
